[package]
name = "miro"
version = "0.1.0"
description = "Terminal emulator"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/miro"

[dependencies]
failure = "0.1.8"
freetype = "0.7.0"
harfbuzz-sys = "0.5.0"
resize = "0.6.2"
servo-fontconfig = "0.5.1"
unicode-width = "0.1.4"
vte = "0.3.2"
xcb = "0.9.0"
unicode-segmentation = "1.7.1"
libc = "0.2.85"
mio = "0.6.12"

[dependencies.xcb-util]
features = [
    "image",
    "icccm",
    "ewmh",
    "misc",
    "shm",
]
version = "0.3.0"