[package]
name = "miro"
version = "0.1.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/miro"

[dependencies]
failure = "0.1.8"
hexdump = "0.1.0"
sdl2 = {version="0.34.3", features=["bundled"]}
vte = "0.10.0"
freetype = "0.7.0"
harfbuzz-sys = "0.5.0"
servo-fontconfig = "0.5.1"